// Project: Logik und Mengenlehre
// Generated by HelpNDoc - https://www.helpndoc.com

unit 5473;

interface

const
  // Format: HELP_help-id = help-context
  HELP_Lizenz-Bittelesen = 2; 				 // Topic: "Lizenz - Bitte lesen !!!"
  HELP_GerhardHessenberg = 32; 				 // Topic: "Gerhard Hessenberg"
  HELP_Anhang = 23; 				 // Topic: "Anhang"
  HELP_MIT-Lizenz-Deutsch = 24; 				 // Topic: "MIT - Lizenz - Deutsch"
  HELP_MIT-Lizenz-Englisch = 25; 				 // Topic: "MIT - Lizenz - Englisch"
  HELP_MIT-Lizenz-Franzosisch = 26; 				 // Topic: "MIT - Lizenz - Französisch"
  HELP_MIT-Lizenz-Spanisch = 27; 				 // Topic: "MIT - Lizenz - Spanisch"
  HELP_MIT-Lizenz-Polinsch = 28; 				 // Topic: "MIT - Lizenz - Polinsch"
  HELP_MIT-Lizenz-Russisch = 30; 				 // Topic: "MIT - Lizenz - Russisch"

implementation

end.
