/* Project: DIN 5473 - Logik und Mengenlehre */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __5473_HEADER__
#define __5473_HEADER__

const int HELP_Vorlage = 4; 				 // Topic: "Vorlage"
const int HELP_Lizenz-Bittelesen = 2; 				 // Topic: "Lizenz - Bitte lesen !!!"
const int HELP_Inhalt = 3; 				 // Topic: "Inhalt"
const int HELP_ListederTabellen = 6; 				 // Topic: "Liste der Tabellen"

#endif
