/* Project: DIN 5473 - Logik und Mengenlehre */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __5473Enums_HEADER__
#define __5473Enums_HEADER__

enum {
  HELP_Lizenz-Bittelesen = 2,
  HELP_Uberblick = 0,
  HELP_1FestlegungdesbegrifflichenRahme = 1,
  HELP_11Individuen = 7,
  HELP_12KlassenundMengen = 8,
  HELP_13RelationenundFunktionen = 5,
  HELP_14Objekt-SpracheundMeta-Sprache = 9
};

#endif
