/* Project: DIN 5473 - Logik und Mengenlehre */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __5473Enums_HEADER__
#define __5473Enums_HEADER__

enum {
  HELP_Vorlage = 4,
  HELP_Lizenz-Bittelesen = 2,
  HELP_Inhalt = 3,
  HELP_ListederTabellen = 6
};

#endif
