# Project: DIN 5473 - Logik und Mengenlehre
# Generated by HelpNDoc - https://www.helpndoc.com

from enum import Enum

class Help_5473(Enum):
    Lizenz-Bittelesen = 2
    Uberblick = 0
    Inhalt = 3
    1FestlegungdesbegrifflichenRahme = 1
    11Individuen = 7
    12KlassenundMengen = 8
    13RelationenundFunktionen = 5
    14Objekt-SpracheundMeta-Sprache = 9
    15Variablen = 10
    16Konstanten = 11
    17Formeln = 12
    18Terme = 13
    2Logik = 14
    21Junktoren = 20
    22Quantoren = 21
    23Kennzeichnungs-Operator = 22
    24Modaloperatoren = 33
    25MetatheoretischeOperatoren = 34
    3KlassenundMengen = 15
    4Standard-Zahlen-Mengen = 16
    5Relationen = 17
    6Funktionen = 18
    7Strukturen = 19
    8Kardinalzahlen = 35
    Anhang = 23
    MIT-Lizenz-Deutsch = 24
    MIT-Lizenz-Englisch = 25
    MIT-Lizenz-Franzosisch = 26
    MIT-Lizenz-Spanisch = 27
    MIT-Lizenz-Polinsch = 28
    MIT-Lizenz-Russisch = 30
