# Project: DIN 5473 - Logik und Mengenlehre
# Generated by HelpNDoc - https://www.helpndoc.com

from enum import Enum

class Help_5473(Enum):
    Lizenz-Bittelesen = 2
    Uberblick = 0
    1FestlegungdesbegrifflichenRahme = 1
    11Individuen = 7
    12KlassenundMengen = 8
    13RelationenundFunktionen = 5
    14Objekt-SpracheundMeta-Sprache = 9
