/* Project: DIN 5473 - Logik und Mengenlehre */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __5473Defines_HEADER__
#define __5473Defines_HEADER__

#define HELP_Lizenz-Bittelesen 2
#define HELP_Uberblick 0
#define HELP_Inhalt 3
#define HELP_1FestlegungdesbegrifflichenRahme 1
#define HELP_11Individuen 7
#define HELP_12KlassenundMengen 8
#define HELP_13RelationenundFunktionen 5
#define HELP_14Objekt-SpracheundMeta-Sprache 9
#define HELP_15Variablen 10
#define HELP_16Konstanten 11
#define HELP_17Formeln 12
#define HELP_18Terme 13
#define HELP_2Logik 14
#define HELP_21Junktoren 20
#define HELP_22Quantoren 21
#define HELP_23Kennzeichnungs-Operator 22
#define HELP_24Modaloperatoren 33
#define HELP_25MetatheoretischeOperatoren 34
#define HELP_3KlassenundMengen 15
#define HELP_4Standard-Zahlen-Mengen 16
#define HELP_5Relationen 17
#define HELP_6Funktionen 18
#define HELP_7Strukturen 19
#define HELP_8Kardinalzahlen 35
#define HELP_Anhang 23
#define HELP_MIT-Lizenz-Deutsch 24
#define HELP_MIT-Lizenz-Englisch 25
#define HELP_MIT-Lizenz-Franzosisch 26
#define HELP_MIT-Lizenz-Spanisch 27
#define HELP_MIT-Lizenz-Polinsch 28
#define HELP_MIT-Lizenz-Russisch 30

#endif
