/* Project: Logik und Mengenlehre */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __5473Defines_HEADER__
#define __5473Defines_HEADER__

#define HELP_Lizenz-Bittelesen 2
#define HELP_GerhardHessenberg 32
#define HELP_Anhang 23
#define HELP_MIT-Lizenz-Deutsch 24
#define HELP_MIT-Lizenz-Englisch 25
#define HELP_MIT-Lizenz-Franzosisch 26
#define HELP_MIT-Lizenz-Spanisch 27
#define HELP_MIT-Lizenz-Polinsch 28
#define HELP_MIT-Lizenz-Russisch 30

#endif
