// Project: DIN 5473 - Logik und Mengenlehre
// Generated by HelpNDoc - https://www.helpndoc.com

public enum Help_5473Enums
{
    Vorlage = 4,
    Lizenz-Bittelesen = 2,
    Inhalt = 3,
    ListederTabellen = 6,
}
