# Project: DIN 5473 - Logik und Mengenlehre
# Generated by HelpNDoc - https://www.helpndoc.com

from enum import Enum

class Help_5473(Enum):
    Vorlage = 4
    Lizenz-Bittelesen = 2
    Inhalt = 3
    ListederTabellen = 6
