/* Project: Logik und Mengenlehre */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __5473_HEADER__
#define __5473_HEADER__

const int HELP_Lizenz-Bittelesen = 2; 				 // Topic: "Lizenz - Bitte lesen !!!"
const int HELP_GerhardHessenberg = 32; 				 // Topic: "Gerhard Hessenberg"
const int HELP_Anhang = 23; 				 // Topic: "Anhang"
const int HELP_MIT-Lizenz-Deutsch = 24; 				 // Topic: "MIT - Lizenz - Deutsch"
const int HELP_MIT-Lizenz-Englisch = 25; 				 // Topic: "MIT - Lizenz - Englisch"
const int HELP_MIT-Lizenz-Franzosisch = 26; 				 // Topic: "MIT - Lizenz - Französisch"
const int HELP_MIT-Lizenz-Spanisch = 27; 				 // Topic: "MIT - Lizenz - Spanisch"
const int HELP_MIT-Lizenz-Polinsch = 28; 				 // Topic: "MIT - Lizenz - Polinsch"
const int HELP_MIT-Lizenz-Russisch = 30; 				 // Topic: "MIT - Lizenz - Russisch"

#endif
