/* Project: DIN 5473 - Logik und Mengenlehre */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __5473Defines_HEADER__
#define __5473Defines_HEADER__

#define HELP_Vorlage 4
#define HELP_Lizenz-Bittelesen 2
#define HELP_Inhalt 3
#define HELP_ListederTabellen 6

#endif
