/* Project: DIN 5473 - Logik und Mengenlehre */
/* Generated by HelpNDoc - https://www.helpndoc.com */

#ifndef __5473_HEADER__
#define __5473_HEADER__

const int HELP_Lizenz-Bittelesen = 2; 				 // Topic: "Lizenz - Bitte lesen !!!"
const int HELP_Uberblick = 0; 				 // Topic: "Überblick"
const int HELP_Inhalt = 3; 				 // Topic: "Inhalt"
const int HELP_1FestlegungdesbegrifflichenRahme = 1; 				 // Topic: "1. Festlegung des begrifflichen Rahmens"
const int HELP_11Individuen = 7; 				 // Topic: "1.1. Individuen"
const int HELP_12KlassenundMengen = 8; 				 // Topic: "1.2. Klassen und Mengen"
const int HELP_13RelationenundFunktionen = 5; 				 // Topic: "1.3. Relationen und Funktionen"
const int HELP_14Objekt-SpracheundMeta-Sprache = 9; 				 // Topic: "1.4. Objekt-Sprache und Meta-Sprache"
const int HELP_15Variablen = 10; 				 // Topic: "1.5. Variablen"
const int HELP_16Konstanten = 11; 				 // Topic: "1.6. Konstanten"
const int HELP_17Formeln = 12; 				 // Topic: "1.7. Formeln"
const int HELP_18Terme = 13; 				 // Topic: "1.8. Terme"
const int HELP_2Logik = 14; 				 // Topic: "2. Logik"
const int HELP_21Junktoren = 20; 				 // Topic: "2.1. Junktoren"
const int HELP_22Quantoren = 21; 				 // Topic: "2.2. Quantoren"
const int HELP_23Kennzeichnungs-Operator = 22; 				 // Topic: "2.3. Kennzeichnungs-Operator"
const int HELP_24Modaloperatoren = 33; 				 // Topic: "2.4. Modaloperatoren"
const int HELP_25MetatheoretischeOperatoren = 34; 				 // Topic: "2.5. Metatheoretische Operatoren"
const int HELP_3KlassenundMengen = 15; 				 // Topic: "3. Klassen und Mengen"
const int HELP_4Standard-Zahlen-Mengen = 16; 				 // Topic: "4. Standard-Zahlen-Mengen"
const int HELP_5Relationen = 17; 				 // Topic: "5. Relationen"
const int HELP_6Funktionen = 18; 				 // Topic: "6. Funktionen"
const int HELP_7Strukturen = 19; 				 // Topic: "7. Strukturen"
const int HELP_8Kardinalzahlen = 35; 				 // Topic: "8. Kardinalzahlen"
const int HELP_Anhang = 23; 				 // Topic: "Anhang"
const int HELP_MIT-Lizenz-Deutsch = 24; 				 // Topic: "MIT - Lizenz - Deutsch"
const int HELP_MIT-Lizenz-Englisch = 25; 				 // Topic: "MIT - Lizenz - Englisch"
const int HELP_MIT-Lizenz-Franzosisch = 26; 				 // Topic: "MIT - Lizenz - Französisch"
const int HELP_MIT-Lizenz-Spanisch = 27; 				 // Topic: "MIT - Lizenz - Spanisch"
const int HELP_MIT-Lizenz-Polinsch = 28; 				 // Topic: "MIT - Lizenz - Polinsch"
const int HELP_MIT-Lizenz-Russisch = 30; 				 // Topic: "MIT - Lizenz - Russisch"

#endif
