// Project: DIN 5473 - Logik und Mengenlehre
// Generated by HelpNDoc - https://www.helpndoc.com

unit 5473;

interface

const
  // Format: HELP_help-id = help-context
  HELP_Lizenz-Bittelesen = 2; 				 // Topic: "Lizenz - Bitte lesen !!!"
  HELP_Uberblick = 0; 				 // Topic: "Überblick"
  HELP_Inhalt = 3; 				 // Topic: "Inhalt"
  HELP_1FestlegungdesbegrifflichenRahme = 1; 				 // Topic: "1. Festlegung des begrifflichen Rahmens"
  HELP_11Individuen = 7; 				 // Topic: "1.1. Individuen"
  HELP_12KlassenundMengen = 8; 				 // Topic: "1.2. Klassen und Mengen"
  HELP_13RelationenundFunktionen = 5; 				 // Topic: "1.3. Relationen und Funktionen"
  HELP_14Objekt-SpracheundMeta-Sprache = 9; 				 // Topic: "1.4. Objekt-Sprache und Meta-Sprache"
  HELP_15Variablen = 10; 				 // Topic: "1.5. Variablen"
  HELP_16Konstanten = 11; 				 // Topic: "1.6. Konstanten"
  HELP_17Formeln = 12; 				 // Topic: "1.7. Formeln"
  HELP_18Terme = 13; 				 // Topic: "1.8. Terme"
  HELP_2Logik = 14; 				 // Topic: "2. Logik"
  HELP_21Junktoren = 20; 				 // Topic: "2.1. Junktoren"
  HELP_22Quantoren = 21; 				 // Topic: "2.2. Quantoren"
  HELP_23Kennzeichnungs-Operator = 22; 				 // Topic: "2.3. Kennzeichnungs-Operator"
  HELP_24Modaloperatoren = 33; 				 // Topic: "2.4. Modaloperatoren"
  HELP_25MetatheoretischeOperatoren = 34; 				 // Topic: "2.5. Metatheoretische Operatoren"
  HELP_3KlassenundMengen = 15; 				 // Topic: "3. Klassen und Mengen"
  HELP_4Standard-Zahlen-Mengen = 16; 				 // Topic: "4. Standard-Zahlen-Mengen"
  HELP_5Relationen = 17; 				 // Topic: "5. Relationen"
  HELP_6Funktionen = 18; 				 // Topic: "6. Funktionen"
  HELP_7Strukturen = 19; 				 // Topic: "7. Strukturen"
  HELP_8Kardinalzahlen = 35; 				 // Topic: "8. Kardinalzahlen"
  HELP_Anhang = 23; 				 // Topic: "Anhang"
  HELP_MIT-Lizenz-Deutsch = 24; 				 // Topic: "MIT - Lizenz - Deutsch"
  HELP_MIT-Lizenz-Englisch = 25; 				 // Topic: "MIT - Lizenz - Englisch"
  HELP_MIT-Lizenz-Franzosisch = 26; 				 // Topic: "MIT - Lizenz - Französisch"
  HELP_MIT-Lizenz-Spanisch = 27; 				 // Topic: "MIT - Lizenz - Spanisch"
  HELP_MIT-Lizenz-Polinsch = 28; 				 // Topic: "MIT - Lizenz - Polinsch"
  HELP_MIT-Lizenz-Russisch = 30; 				 // Topic: "MIT - Lizenz - Russisch"

implementation

end.
