# Project: DIN 5473 - Logik und Mengenlehre
# Generated by HelpNDoc - https://www.helpndoc.com

public const HELP_Lizenz-Bittelesen as integer = 2
public const HELP_Uberblick as integer = 0
public const HELP_1FestlegungdesbegrifflichenRahme as integer = 1
public const HELP_11Individuen as integer = 7
public const HELP_12KlassenundMengen as integer = 8
public const HELP_13RelationenundFunktionen as integer = 5
public const HELP_14Objekt-SpracheundMeta-Sprache as integer = 9
