# Project: DIN 5473 - Logik und Mengenlehre
# Generated by HelpNDoc - https://www.helpndoc.com

public const HELP_Vorlage as integer = 4
public const HELP_Lizenz-Bittelesen as integer = 2
public const HELP_Inhalt as integer = 3
public const HELP_ListederTabellen as integer = 6
