// Project: DIN 5473 - Logik und Mengenlehre
// Generated by HelpNDoc - https://www.helpndoc.com

unit 5473;

interface

const
  // Format: HELP_help-id = help-context
  HELP_Vorlage = 4; 				 // Topic: "Vorlage"
  HELP_Lizenz-Bittelesen = 2; 				 // Topic: "Lizenz - Bitte lesen !!!"
  HELP_Inhalt = 3; 				 // Topic: "Inhalt"
  HELP_ListederTabellen = 6; 				 // Topic: "Liste der Tabellen"

implementation

end.
