# Project: DIN 5473 - Logik und Mengenlehre
# Generated by HelpNDoc - https://www.helpndoc.com

public const HELP_Lizenz-Bittelesen as integer = 2
public const HELP_Uberblick as integer = 0
public const HELP_Inhalt as integer = 3
public const HELP_1FestlegungdesbegrifflichenRahme as integer = 1
public const HELP_11Individuen as integer = 7
public const HELP_12KlassenundMengen as integer = 8
public const HELP_13RelationenundFunktionen as integer = 5
public const HELP_14Objekt-SpracheundMeta-Sprache as integer = 9
public const HELP_15Variablen as integer = 10
public const HELP_16Konstanten as integer = 11
public const HELP_17Formeln as integer = 12
public const HELP_18Terme as integer = 13
public const HELP_2Logik as integer = 14
public const HELP_21Junktoren as integer = 20
public const HELP_22Quantoren as integer = 21
public const HELP_23Kennzeichnungs-Operator as integer = 22
public const HELP_24Modaloperatoren as integer = 33
public const HELP_25MetatheoretischeOperatoren as integer = 34
public const HELP_3KlassenundMengen as integer = 15
public const HELP_4Standard-Zahlen-Mengen as integer = 16
public const HELP_5Relationen as integer = 17
public const HELP_6Funktionen as integer = 18
public const HELP_7Strukturen as integer = 19
public const HELP_8Kardinalzahlen as integer = 35
public const HELP_Anhang as integer = 23
public const HELP_MIT-Lizenz-Deutsch as integer = 24
public const HELP_MIT-Lizenz-Englisch as integer = 25
public const HELP_MIT-Lizenz-Franzosisch as integer = 26
public const HELP_MIT-Lizenz-Spanisch as integer = 27
public const HELP_MIT-Lizenz-Polinsch as integer = 28
public const HELP_MIT-Lizenz-Russisch as integer = 30
